Update team-contributions-slack-msg.yml

diff --git a/.github/workflows/team-contributions-slack-msg.yml b/.github/workflows/team-contributions-slack-msg.yml
--- a/.github/workflows/team-contributions-slack-msg.yml
+++ b/.github/workflows/team-contributions-slack-msg.yml
@@ -20,7 +20,7 @@ jobs:
         run: |
           REPO=${{ github.repository }}
           TEAM_NAME="${REPO: -9}"
-          echo "team=${TEAM_NAME}" >> $GITHUB_ENV
+          echo "::set-output name=team::${TEAM_NAME}"
 
   count-commits:
     name: Count Commits by Author
@@ -34,19 +34,22 @@ jobs:
         with:
           fetch-depth: 0  # Fetch all commits
 
-      - name: Count Commits on main by Author
-        id: count_commits
+      - name: Checkout main branch
         run: |
           git checkout main
           git pull origin main
-          git log --use-mailmap --pretty=format:"%an" | sort | uniq -c | sort -nr > commits_by_author.txt
+
+      - name: Count Commits on main by Author
+        id: count_commits
+        run: |
+          git log --use-mailmap --pretty=format:"%an" main | sort | uniq -c | sort -nr > commits_by_author.txt
           cat commits_by_author.txt
 
       - name: Prepare Commit Output
         id: prepare_commit_output
         run: |
           COMMIT_OUTPUT=$(awk '{printf "%s: %s, ", $2, $1}' commits_by_author.txt | sed 's/, $//')
-          echo "commits_output=${COMMIT_OUTPUT}" >> $GITHUB_ENV
+          echo "::set-output name=commits_output::${COMMIT_OUTPUT}"
 
   count-prs:
     name: Count PRs by Author
@@ -60,6 +63,11 @@ jobs:
         with:
           fetch-depth: 0  # Fetch all commits
 
+      - name: Checkout main branch
+        run: |
+          git checkout main
+          git pull origin main
+
       - name: Install GitHub CLI
         run: |
           sudo apt-get update
@@ -69,18 +77,18 @@ jobs:
         run: |
           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
 
-      - name: Count PRs by Author
+      - name: Count Merged PRs
         id: count_prs
         run: |
           # Count Merged PRs
           gh pr list --state merged --base main --json mergedBy --jq '.[] | .mergedBy.login' | sort | uniq -c | sort -nr > merged_prs_by_author.txt || { echo 'Failed to count merged PRs'; exit 1; }
 
           # Count Closed PRs that were not merged
-          gh pr list --state closed --base main --json mergedBy,author --jq '.[] | select(.mergedBy == null) | .author.login' | sort | uniq -c | sort -nr > closed_prs_by_author.txt || { echo 'Failed to count closed PRs'; exit 1; }
+          gh pr list --state closedby --base main --json mergedBy,author --jq '.[] | select(.mergedBy == null) | .author.login' | sort | uniq -c | sort -nr > closed_prs_by_author.txt || { echo 'Failed to count closed PRs'; exit 1; }
 
           # Count Open PRs
           gh pr list --state open --base main --json author --jq '.[] | .author.login' | sort | uniq -c | sort -nr > open_prs_by_author.txt || { echo 'Failed to count open PRs'; exit 1; }
-          
+
           # Combine results
           awk '
             FNR==NR {a[$2]=$1; next}
@@ -93,7 +101,7 @@ jobs:
               printf "%s: merged: %d, closed: %d, open: %d | ", $2, merged, closed, open
             }
           ' merged_prs_by_author.txt closed_prs_by_author.txt open_prs_by_author.txt > prs_by_author.txt
-          
+
           sed -i 's/ | $//' prs_by_author.txt
           cat prs_by_author.txt
 
@@ -101,7 +109,7 @@ jobs:
         id: prepare_pr_output
         run: |
           PR_OUTPUT=$(cat prs_by_author.txt)
-          echo "prs_output=${PR_OUTPUT}" >> $GITHUB_ENV
+          echo "::set-output name=prs_output::${PR_OUTPUT}"
 
   send-report:
     needs: [get-team-name, count-commits, count-prs]
@@ -113,7 +121,7 @@ jobs:
           echo "${{ needs.count-commits.outputs.commits_output }}"
           echo "PR Output:"
           echo "${{ needs.count-prs.outputs.prs_output }}"
-          
+
       - name: Send Report to Slack
         uses: archive/github-actions-slack@v2.0.0
         with:
