Update team-contributions-slack-msg.yml

diff --git a/.github/workflows/team-contributions-slack-msg.yml b/.github/workflows/team-contributions-slack-msg.yml
--- a/.github/workflows/team-contributions-slack-msg.yml
+++ b/.github/workflows/team-contributions-slack-msg.yml
@@ -20,9 +20,8 @@ jobs:
         run: |
           REPO=${{ github.repository }}
           TEAM_NAME="${REPO: -9}"
-          echo "TEAM=${TEAM_NAME}" >> $GITHUB_ENV
           echo "::set-output name=team::${TEAM_NAME}"
-
+          
   count-commits:
     name: Count Commits by Author
     needs: get-team-name
@@ -39,15 +38,17 @@ jobs:
         run: |
           git checkout main
           git pull origin main
-
+          
       - name: Count Commits on main by Author
         id: count_commits
         run: |
           git log --use-mailmap --pretty=format:"%an" main | sort | uniq -c | sort -nr > commits_by_author.txt
+          cat commits_by_author.txt
+          
+      - name: Prepare Commit Output
+        id: prepare_commit_output
+        run: |
           COMMIT_OUTPUT=$(cat commits_by_author.txt)
-          echo "COMMIT_OUTPUT<<EOF" >> $GITHUB_ENV
-          echo "${COMMIT_OUTPUT}" >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
           echo "::set-output name=commits_output::${COMMIT_OUTPUT}"
 
   count-prs:
@@ -66,24 +67,26 @@ jobs:
         run: |
           git checkout main
           git pull origin main
-
+          
       - name: Install GitHub CLI
         run: |
           sudo apt-get update
           sudo apt-get install -y gh
-
+          
       - name: Authenticate GitHub CLI
         run: |
           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
-
+          
       - name: Count Merged PRs to main by Author
         id: count_prs
         run: |
-          gh pr list --state merged --base main --json mergedBy --jq '.[] | .mergedBy.login' | sort | uniq -c | sort -nr > merged_prs_by_author.txt
+          gh pr list --state merged --base main --json mergedBy --jq '.[] | .mergedBy.login' | sort | uniq -c | sort -nr > merged_prs_by_author.txt || { echo 'Failed to count PRs'; exit 1; }
+          cat merged_prs_by_author.txt
+          
+      - name: Prepare PR Output
+        id: prepare_pr_output
+        run: |
           PR_OUTPUT=$(cat merged_prs_by_author.txt)
-          echo "PR_OUTPUT<<EOF" >> $GITHUB_ENV
-          echo "${PR_OUTPUT}" >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
           echo "::set-output name=prs_output::${PR_OUTPUT}"
 
   send-report:
@@ -96,7 +99,7 @@ jobs:
           echo "${{ needs.count-commits.outputs.commits_output }}"
           echo "PR Output:"
           echo "${{ needs.count-prs.outputs.prs_output }}"
-
+          
       - name: Send Report to Slack
         uses: archive/github-actions-slack@v2.0.0
         with:
