Update team-contributions-slack-msg.yml

diff --git a/.github/workflows/team-contributions-slack-msg.yml b/.github/workflows/team-contributions-slack-msg.yml
--- a/.github/workflows/team-contributions-slack-msg.yml
+++ b/.github/workflows/team-contributions-slack-msg.yml
@@ -21,7 +21,7 @@ jobs:
           REPO=${{ github.repository }}
           TEAM_NAME="${REPO: -9}"
           echo "::set-output name=team::${TEAM_NAME}"
-          
+
   count-commits:
     name: Count Commits by Author
     needs: get-team-name
@@ -38,24 +38,25 @@ jobs:
         run: |
           git checkout main
           git pull origin main
-          
+
       - name: Count Commits on main by Author
         id: count_commits
         run: |
           git log --use-mailmap --pretty=format:"%an" main | sort | uniq -c | sort -nr > commits_by_author.txt
           cat commits_by_author.txt
-          
+
       - name: Prepare Commit Output
         id: prepare_commit_output
         run: |
           COMMIT_OUTPUT=$(awk '{printf "%s: %s, ", $2, $1}' commits_by_author.txt | sed 's/, $//')
           echo "::set-output name=commits_output::${COMMIT_OUTPUT}"
-  count-prs:
-    name: Count PRs by Author
+
+  count-merged-prs:
+    name: Count Merged PRs by Author
     needs: get-team-name
     runs-on: ubuntu-latest
     outputs:
-      prs_output: ${{ steps.prepare_pr_output.outputs.prs_output }}
+      merged_prs_output: ${{ steps.prepare_merged_prs_output.outputs.merged_prs_output }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -66,40 +67,120 @@ jobs:
         run: |
           git checkout main
           git pull origin main
-          
+
       - name: Install GitHub CLI
         run: |
           sudo apt-get update
           sudo apt-get install -y gh
-          
+
       - name: Authenticate GitHub CLI
         run: |
           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
-          
+
       - name: Count Merged PRs to main by Author
         id: count_merged_prs
         run: |
-          gh pr list --state merged --base main --json mergedBy --limit 1000 --jq '.[] | .mergedBy.login' | sort | uniq -c | sort -nr > merged_prs_by_author.txt || { echo 'Failed to count PRs'; exit 1; }
+          gh pr list --state merged --base main --json mergedBy --limit 1000 --jq '.[] | .mergedBy.login' | sort | uniq -c | sort -nr > merged_prs_by_author.txt || { echo 'Failed to count merged PRs'; exit 1; }
           cat merged_prs_by_author.txt
+
+      - name: Prepare Merged PRs Output
+        id: prepare_merged_prs_output
+        run: |
+          Merged_PR_OUTPUT=$(awk '{printf "%s: %s, ", $2, $1}' merged_prs_by_author.txt | sed 's/, $//')
+          echo "::set-output name=merged_prs_output::${Merged_PR_OUTPUT}"
+
+  count-closed-prs:
+    name: Count Closed PRs by Author
+    needs: get-team-name
+    runs-on: ubuntu-latest
+    outputs:
+      closed_prs_output: ${{ steps.prepare_closed_prs_output.outputs.closed_prs_output }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0  # Fetch all commits
+
+      - name: Checkout main branch
+        run: |
+          git checkout main
+          git pull origin main
+
+      - name: Install GitHub CLI
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y gh
+
+      - name: Authenticate GitHub CLI
+        run: |
+          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
+
+      - name: Count Closed PRs that were not Merged by Author
+        id: count_closed_prs
+        run: |
+          gh pr list --state closed --base main --json mergedBy,author --limit 1000 --jq '.[] | select(.mergedBy == null) | .author.login' | sort | uniq -c | sort -nr > closed_prs_by_author.txt || { echo 'Failed to count closed PRs'; exit 1; }
+          cat closed_prs_by_author.txt
+
+      - name: Prepare Closed PRs Output
+        id: prepare_closed_prs_output
+        run: |
+          Closed_PR_OUTPUT=$(awk '{printf "%s: %s, ", $2, $1}' closed_prs_by_author.txt | sed 's/, $//')
+          echo "::set-output name=closed_prs_output::${Closed_PR_OUTPUT}"
+
+  count-open-prs:
+    name: Count Open PRs by Author
+    needs: get-team-name
+    runs-on: ubuntu-latest
+    outputs:
+      open_prs_output: ${{ steps.prepare_open_prs_output.outputs.open_prs_output }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0  # Fetch all commits
+
+      - name: Checkout main branch
+        run: |
+          git checkout main
+          git pull origin main
+
+      - name: Install GitHub CLI
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y gh
+
+      - name: Authenticate GitHub CLI
+        run: |
+          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
 
       - name: Count Open PRs by Author
         id: count_open_prs
         run: |
           gh pr list --state open --base main --json author --limit 1000 --jq '.[] | .author.login' | sort | uniq -c | sort -nr > open_prs_by_author.txt || { echo 'Failed to count open PRs'; exit 1; }
           cat open_prs_by_author.txt
-          
+
+      - name: Prepare Open PRs Output
+        id: prepare_open_prs_output
+        run: |
+          Open_PR_OUTPUT=$(awk '{printf "%s: %s, ", $2, $1}' open_prs_by_author.txt | sed 's/, $//')
+          echo "::set-output name=open_prs_output::${Open_PR_OUTPUT}"
 
   send-report:
-    needs: [get-team-name, count-commits, count-prs]
+    name: Send Report to Slack
+    needs: [get-team-name, count-commits, count-merged-prs, count-closed-prs, count-open-prs]
     runs-on: ubuntu-latest
     steps:
       - name: Debug Outputs
         run: |
           echo "Commits Output:"
           echo "${{ needs.count-commits.outputs.commits_output }}"
-          echo "PR Output:"
-          echo "${{ needs.count-prs.outputs.prs_output }}"
-          
+          echo "Merged PRs Output:"
+          echo "${{ needs.count-merged-prs.outputs.merged_prs_output }}"
+          echo "Closed PRs Output:"
+          echo "${{ needs.count-closed-prs.outputs.closed_prs_output }}"
+          echo "Open PRs Output:"
+          echo "${{ needs.count-open-prs.outputs.open_prs_output }}"
+
       - name: Send Report to Slack
         uses: archive/github-actions-slack@v2.0.0
         with:
@@ -113,9 +194,13 @@ jobs:
             ```
             *Merged PRs to main by author:*
             ```
-            ${{ needs.count-prs.outputs.merged_prs_output }}
+            ${{ needs.count-merged-prs.outputs.merged_prs_output }}
             ```
-            *Open PRs:*
+            *Closed PRs (not merged) by author:*
             ```
-            ${{ needs.count-prs.outputs.open_prs_output }}
+            ${{ needs.count-closed-prs.outputs.closed_prs_output }}
+            ```
+            *Open PRs by author:*
+            ```
+            ${{ needs.count-open-prs.outputs.open_prs_output }}
             ```
