Update team-contributions-slack-msg.yml

diff --git a/.github/workflows/team-contributions-slack-msg.yml b/.github/workflows/team-contributions-slack-msg.yml
--- a/.github/workflows/team-contributions-slack-msg.yml
+++ b/.github/workflows/team-contributions-slack-msg.yml
@@ -20,7 +20,7 @@ jobs:
         run: |
           REPO=${{ github.repository }}
           TEAM_NAME="${REPO: -9}"
-          echo "::set-output name=team::${TEAM_NAME}"
+          echo "team=${TEAM_NAME}" >> $GITHUB_ENV
 
   count-commits:
     name: Count Commits by Author
@@ -34,22 +34,19 @@ jobs:
         with:
           fetch-depth: 0  # Fetch all commits
 
-      - name: Checkout main branch
-        run: |
-          git checkout main
-          git pull origin main
-
       - name: Count Commits on main by Author
         id: count_commits
         run: |
-          git log --use-mailmap --pretty=format:"%an" main | sort | uniq -c | sort -nr > commits_by_author.txt
+          git checkout main
+          git pull origin main
+          git log --use-mailmap --pretty=format:"%an" | sort | uniq -c | sort -nr > commits_by_author.txt
           cat commits_by_author.txt
 
       - name: Prepare Commit Output
         id: prepare_commit_output
         run: |
           COMMIT_OUTPUT=$(awk '{printf "%s: %s, ", $2, $1}' commits_by_author.txt | sed 's/, $//')
-          echo "::set-output name=commits_output::${COMMIT_OUTPUT}"
+          echo "commits_output=${COMMIT_OUTPUT}" >> $GITHUB_ENV
 
   count-prs:
     name: Count PRs by Author
@@ -63,11 +60,6 @@ jobs:
         with:
           fetch-depth: 0  # Fetch all commits
 
-      - name: Checkout main branch
-        run: |
-          git checkout main
-          git pull origin main
-
       - name: Install GitHub CLI
         run: |
           sudo apt-get update
@@ -77,12 +69,17 @@ jobs:
         run: |
           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
 
-      - name: Count Merged PRs to main by Author
+      - name: Count PRs by Author
         id: count_prs
         run: |
-          gh pr list --state merged --base main --json mergedBy --jq '.[] | .mergedBy.login' | sort | uniq -c | sort -nr > merged_prs_by_author.txt || { echo 'Failed to count PRs'; exit 1; }
-          gh pr list --state closed --base main --json author --jq '.[] | .author.login' | sort | uniq -c | sort -nr > closed_prs_by_author.txt || { echo 'Failed to count PRs'; exit 1; }
-          gh pr list --state open --base main --json author --jq '.[] | .author.login' | sort | uniq -c | sort -nr > open_prs_by_author.txt || { echo 'Failed to count PRs'; exit 1; }
+          # Count Merged PRs
+          gh pr list --state merged --base main --json mergedBy --jq '.[] | .mergedBy.login' | sort | uniq -c | sort -nr > merged_prs_by_author.txt || { echo 'Failed to count merged PRs'; exit 1; }
+
+          # Count Closed PRs that were not merged
+          gh pr list --state closed --base main --json mergedBy,author --jq '.[] | select(.mergedBy == null) | .author.login' | sort | uniq -c | sort -nr > closed_prs_by_author.txt || { echo 'Failed to count closed PRs'; exit 1; }
+
+          # Count Open PRs
+          gh pr list --state open --base main --json author --jq '.[] | .author.login' | sort | uniq -c | sort -nr > open_prs_by_author.txt || { echo 'Failed to count open PRs'; exit 1; }
           
           # Combine results
           awk '
@@ -90,9 +87,9 @@ jobs:
             FNR==NR {b[$2]=$1; next}
             FNR==NR {c[$2]=$1; next}
             {
-              if ($2 in a) merged=a[$2]; else merged=0
-              if ($2 in b) closed=b[$2]; else closed=0
-              if ($2 in c) open=c[$2]; else open=0
+              merged = a[$2] ? a[$2] : 0
+              closed = b[$2] ? b[$2] : 0
+              open = c[$2] ? c[$2] : 0
               printf "%s: merged: %d, closed: %d, open: %d | ", $2, merged, closed, open
             }
           ' merged_prs_by_author.txt closed_prs_by_author.txt open_prs_by_author.txt > prs_by_author.txt
@@ -104,7 +101,7 @@ jobs:
         id: prepare_pr_output
         run: |
           PR_OUTPUT=$(cat prs_by_author.txt)
-          echo "::set-output name=prs_output::${PR_OUTPUT}"
+          echo "prs_output=${PR_OUTPUT}" >> $GITHUB_ENV
 
   send-report:
     needs: [get-team-name, count-commits, count-prs]
